[package]
name = "cw20-staking"
version = "0.1.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../common" }
common-derive = { path = "../common-derive" }
cosmwasm-std = "1"
cosmwasm-storage = "1"
cosmwasm-schema = "1.1"
cw-asset = "2.2"
cw-storage-plus = "0.16"
cw-utils = "0.16"
cw2 = "0.16"
cw20-base = "0.16"
cw20 = "0.16"
itertools = "0.10"
schemars = "0.8"
serde = { version = "1", default-features = false, features = ["derive"] }
serde_with = { version = "2", features = ["json", "macros"] }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1"

[dev-dependencies]
cosmwasm-schema = "1"
cw-multi-test = "0.15"
